name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs and Material Theme
        run: pip install mkdocs-material

      - name: Build MkDocs Site to 'docs-site' Folder
        run: mkdocs build --site-dir docs-site

      - name: Commit Built Site Folder to Branch
        run: |
          git add docs-site
          git commit -m "Deploy MkDocs site to docs-site folder" || echo "No changes to commit"
          git push




#   deploy-pages:
#     needs: deploy
#     runs-on: ubuntu-latest
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v2

# name: ci

# on:
#   push:
#     branches:
#       - main
#       - master

# permissions:
#   contents: write

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.x

#       - run: pip install mkdocs-material

#       - name: Deploy MkDocs Site
#         run: mkdocs gh-deploy --force --remote-branch main




